<a href="https://colab.research.google.com/github/b-sierra/rps/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu121


## intro to tensors

### creating tensors

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# get tensor back as python int
scalar.item()

7

In [ ]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# matrix
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX.shape
# two seperate brackets, two elements by two elements

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                      [3, 6, 9],
                      [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
tensor = torch.tensor([[[12, 2, 2],
                        [6, 3, 4],
                        [1, 6, 12]]])

tensor([[12,  2,  2],
        [ 6,  3,  4],
        [ 1,  6, 12]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor.shape

torch.Size([1, 3, 3])

In [ ]:
tensor[0,:,1]

tensor([2, 3, 6])

## Random tensors

Why random tensors?

Important because the way neural networks learn is that they start with tensors full of random numbers then adjust numbers to better represent the data

'Start with random numbers > look at data > update random numbers > look at data > update random numbers'

In [ ]:
# create random tensors of shape/size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4787, 0.7358, 0.7970, 0.6314],
        [0.8499, 0.5907, 0.5012, 0.1185],
        [0.4073, 0.6664, 0.9183, 0.5075]])

In [ ]:
# create random tensor w/ similar shape to image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zero and ones

In [ ]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# create tensor of ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor

tensor([[0.4787, 0.7358, 0.7970, 0.6314],
        [0.8499, 0.5907, 0.5012, 0.1185],
        [0.4073, 0.6664, 0.9183, 0.5075]])

### creating range of tensors and tensors-like

In [ ]:
# use torch.range() and get deprecated message, use torch.arange() w/ start and step
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### tensor datatypes

Tensor datatypes is one of the big 3 errors you will run into w/ pytorch & deep learning
1. Tensors not right Datatype
2. Tensors not right shape
3. Tensors not on right device

How computers store numbers ^

In [ ]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                                dtype=torch.float16, # what datatype is the tensor (e.g. float32 or float16)
                                device=None, # what device is your tensor on
                                requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_32_tensor.dtype

torch.float16

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int64)
int_32_tensor

tensor([3, 6, 9])

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

### getting info from tensors (tensor attributes)

1. Tensors not right Datatype - to get datatype from a tensor, can use 'tensor.dtype'
2. Tensors not right shape - to get shape from a tensor, can use 'tensor.shape'
3. Tensors not on right device - to get device from a tensor, can use 'tensor.device'

In [ ]:
# create tensor
some_tensor = torch.rand(3, 4,
                         dtype=torch.float16,
                         )
some_tensor

tensor([[0.1079, 0.5073, 0.1104, 0.8667],
        [0.0854, 0.5728, 0.1489, 0.3525],
        [0.2803, 0.1011, 0.8662, 0.9263]], dtype=torch.float16)

In [ ]:
some_tensor.size(), some_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [ ]:
# find details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.1079, 0.5073, 0.1104, 0.8667],
        [0.0854, 0.5728, 0.1489, 0.3525],
        [0.2803, 0.1011, 0.8662, 0.9263]], dtype=torch.float16)
Datatype of tensor: torch.float16
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [ ]:
### manipulating Tensors (tensor operations)

Tensor operations include:
* addition
* subtraction
* multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
# create a tensor, add 10
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# multiply tensor by 10
tensor * 10
tensor

tensor([1, 2, 3])

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
# subtract 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# try out pytorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### matrix multiplication

two main ways of performing mulitplication in neural networks and deep learning

1. Element-wise multiplication
2. Matrix multiplication (dot product)

Two main rules performing matrix multiplication needs to satisfy:
1. *inner dimensions* must match:
*(3,2) @ (3,2) won't work
*(2,3) @ (3,2) will work
(3,2) @ (2,3) will work
2. The resulting matrix has the shape of the *outer dimension*:
*(2,3) @ (3,2) > (2,2)
*(3,2) @ (2,3) > (3,3)


In [ ]:
torch.matmul(torch.rand(10,10), torch.rand(10,10)).shape

torch.Size([10, 10])

In [ ]:
# element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
# matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [ ]:
##time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)


In [ ]:
##time
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
### one of most common errors in deep learning: shape errors

In [ ]:
# shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9,12]])
torch.mm(tensor_A, tensor_B) # torch.mm same as torch.matmul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

# To fix tensor shape issues, we can manipulate shape of tensor using **transpose**

A **transpose** switches axes or dimensions of a given tensor

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [ ]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above, tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} < inner dimensions must match")
print("Output:\n")
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above, tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) < inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## finding the min, max, mean, sum, etc (tensor aggregation (large amnt of numbers to small amount of numbers))

In [ ]:
# create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# find max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# find mean - note: torch.mean() function requires tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# find sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## finding positional min max

In [ ]:
# find position in tensor that has minimum value with argmin() > returns index position of target tensor where minimum value occurs
x.argmin()

tensor(0)

In [ ]:
x[1]

tensor(10)

In [ ]:
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(90)

## reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes input tensor to defined shape
* View - Return a view of an input tensor of cerrtain shape but keep same memory as original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all '1' dimensions from a  tensor
* Unsqueeze - add a '1' dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

(manipulate tensor to change shape/dimension)
(#1 issue in ml = tensor shape issues)



In [ ]:
# let's create a tensor

x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# changing z changes x (because view of a tensor shares same memory as original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor (1's)
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
# torch.unsqueeze() - adds single dimension to target tensor at specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add extra dimension
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [ ]:
# torch.permute - rearranges dimensions of target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]

# permute original tensor to rearrange axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0>1, 1>2, 2>0

print(f"previous shape: {x_original.shape}")
print(f"new shape: {x_permuted.shape}") # [color_channels, height, width]

previous shape: torch.Size([224, 224, 3])
new shape: torch.Size([3, 224, 224])


In [ ]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x_reshaped.squeeze().shape

torch.Size([9])

## indexing (selecting data from tensors)

indexing with pytorch similar to indexing with NumPy

In [ ]:
# create tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# lets index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# lets index on the middle brack (dim=1)(index)
x[0][0]

tensor([1, 2, 3])

In [ ]:
# lets index on most inner bracket (last dimension)(element)
x[0][2][2]

tensor(9)

In [ ]:
# you can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# get all values of 0th and 1st dimension but only index 1 of 2nd dimension
x[:, :, 2]

tensor([[3, 6, 9]])

In [ ]:
# get all values of 0th dimension but only 1 index value of 1st and 2nd dimension (square bracket remains because we are selecting all of the 0th dimension)
x[:, 1, 1]

tensor([5])

In [ ]:
# get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

## Pytorch tensors & NumPy

NumPy is a popular scientific python numerical computing library

And because of this, Pytorch has functionality to interact with it

* Data in NumPy, want in PyTorch tensor > 'torch.from_numpy(ndarray)'
* PyTorch tensor > NumPy > 'torch.Tensor.nump()'

In [ ]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32) # warning: when converting nump > pyrtorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# change the value of array, what will this do to 'tensor'? (use from_numpy, we get new tensor in memory)
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# change the tensor, what happens to 'numpy_tensor'? (changes, numpy_tensor stays the same, doesn't share memory)
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## reproducibility (trying to take random out of random)

In short how a neural network learns:

'start with random numbers > tensor operations > update random numbers to try and make them better representations of the data > again > again > again...'

to reduce the randomness in neural networks and pytorch comes the concept of a **random seed**

essentially what the random seed does is "flavor" the randomness.

In [ ]:
# Create two random tensor
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3 ,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.4526, 0.0104, 0.4651, 0.3636],
        [0.1750, 0.6300, 0.1791, 0.9180],
        [0.1874, 0.6119, 0.8185, 0.9080]])
tensor([[0.4654, 0.7021, 0.3542, 0.5322],
        [0.5517, 0.4251, 0.1287, 0.8547],
        [0.7715, 0.8219, 0.4212, 0.4868]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# lets make some random but reproducible tensors

# set the random seed
RANDOM_SEED = 420
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8054, 0.1990, 0.9759, 0.1028],
        [0.3475, 0.1554, 0.8856, 0.6876],
        [0.2506, 0.1133, 0.2105, 0.4035]])
tensor([[0.8054, 0.1990, 0.9759, 0.1028],
        [0.3475, 0.1554, 0.8856, 0.6876],
        [0.2506, 0.1133, 0.2105, 0.4035]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## running tensors and PyTorch objects on GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes making everything good

### 1. Getting a GPU

1. Easiest - using google colab for a GPU (options to upgrade as well)
2. Use own GPU - takes setup and investment, lots of options...
3. Use cloud computing - GCP, AWS, Azure, these services allow to rent computers on cloud and access them

for 2, 3 Pytorch + GPU drivers (CUDA) takes some setting up, refer to PyTorch setup documentation

In [ ]:
invidia-smi

### Check for GPU access with PyTorch

In [ ]:
# check for GPU access with PyTorch
import torch.cuda.is_available()

SyntaxError: invalid syntax (<ipython-input-12-b49da5656b73>, line 2)

In [ ]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# count number of devices
torch.cuda.device_count()

## 3. Putting tensors (and models) on the gpu

tensors/models on GPU because GPU = faster computations

In [ ]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# move tensor to GPU (if available) (to.(device) is goated)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to CPU

In [ ]:
# if tensor is on GPU, cant transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# to fix GPU tensor with NumPy issue, first set it to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
## Exercises and extra-curriculum
